### ISSUE TITLE
Failed to load weights

### ISSUE THREAD

**Issue by checkpoint214159** [Visual-Behavior/detr-tensorflow#50]
When running finetune_voc.py, an error occurs during the loading of weights. It is as follows:

Traceback (most recent call last):
  File "C:\Users\Goh\detr-transformer\detr-tensorflow\finetune_voc.py", line 126, in <module>
    run_finetuning(config)
  File "C:\Users\Goh\detr-transformer\detr-tensorflow\finetune_voc.py", line 77, in run_finetuning
    detr = build_model(config)
  File "C:\Users\Goh\detr-transformer\detr-tensorflow\finetune_voc.py", line 50, in build_model
    detr = get_detr_model(config, include_top=False, weights="detr", num_decoder_layers=6, num_encoder_layers=6)
  File "C:\Users\Goh\detr-transformer\detr-tensorflow\detr_tf\networks\detr.py", line 139, in get_detr_model
    load_weights(detr, weights)
  File "C:\Users\Goh\detr-transformer\detr-tensorflow\detr_tf\networks\weights.py", line 39, in load_weights
    l = model.load_weights(os.path.join(wdir, f"{weights}.ckpt"))
  File "C:\Users\Goh\detr-transformer\detr-tensorflow\venv\lib\site-packages\keras\src\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Goh\detr-transformer\detr-tensorflow\venv\lib\site-packages\tensorflow\python\training\py_checkpoint_reader.py", line 45, in error_translator
    raise errors_impl.OpError(None, None, error_message, errors_impl.UNKNOWN)
tensorflow.python.framework.errors_impl.OpError: not an sstable (bad magic number)

I have tried editing the argument for load_weights to os.path.join(wdir, f"{weights}.ckpt.index") and others, including dowloading the hdf5 file, but to no avail. Any help on this would be much appreciated, especially since no one else seems to have had this issue!

Further contexts (in text since can't upload images for some reason):
- checkpoint, ckpt.index and ckpt.data-00000-of-00001 files are 1KB large, are they supposed to be that size? 
- no other code was changed
- python version 3.9.0
- the WEIGHT_NAME_TO_CKPT dictionary of the api calls should be the same, but in case it isn't here is mine: 
WEIGHT_NAME_TO_CKPT = {
    "detr": [
        "https://storage.googleapis.com/visualbehavior-publicweights/detr/checkpoint",
        "https://storage.googleapis.com/visualbehavior-publicweights/detr/detr.ckpt.data-00000-of-00001",
        "https://storage.googleapis.com/visualbehavior-publicweights/detr/detr.ckpt.index"
    ]
}

(this is my first ever issue/post on github sorry if its all messy or uninformative haha)

**Comment by checkpoint214159** [comment]
Nevermind, found out the problem. They closed their billing account so the weights can no longer downloaded. Oh well.
